### ISSUE TITLE
[Reckie] SheetWrapper 元件滿版高度沒包含到 Navbar

### ISSUE THREAD

**Issue by qw050123** [erik1110/SuperHandy-frontend#24]
建議把 h-full 更改成 h-100，畢竟這邊暫時沒有考慮 footer，那是不是就不用讓使用者往下滾動 Y 軸了
h-100 會繼承到 flex 內的 v-main 高度

**Comment by rere2133** [comment]
小修正，加到[feature/useFetch_v2](https://github.com/erik1110/SuperHandy-frontend/tree/feature/useFetch_v2)裡面，待之後merge dev
